sonar.projectKey=KayPham05_TrelloAppClone_V2
sonar.organization=kaypham05
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/vendor/**,**/*.test.*
# Fix lỗi C/C++/Objective-C
sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-
