// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoAppAPI.Data;

#nullable disable

namespace TodoAppAPI.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20260604135737_AddAnalysisReports")]
    partial class AddAnalysisReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoAppAPI.Models.Activity", b =>
                {
                    b.Property<string>("ActivityUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Action")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CardUId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserUId")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ActivityUId");

                    b.HasIndex("CardUId");

                    b.HasIndex("UserUId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.AnalysisReport", b =>
                {
                    b.Property<string>("ReportUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneratedByUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ModelUsed")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OverallProgress")
                        .HasColumnType("int");

                    b.Property<string>("ReportData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScopeUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ReportUId");

                    b.HasIndex("GeneratedByUId");

                    b.HasIndex("ScopeType", "ScopeUId", "GeneratedAt");

                    b.ToTable("AnalysisReports", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Board", b =>
                {
                    b.Property<string>("BoardUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("AllowMemberJoinCard")
                        .HasColumnType("bit");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoardName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Private");

                    b.Property<string>("WorkspaceUId")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("BoardUId");

                    b.HasIndex("WorkspaceUId");

                    b.HasIndex("UserUId", "IsPersonal");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.BoardMember", b =>
                {
                    b.Property<string>("BoardMemberUId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BoardRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Viewer");

                    b.Property<string>("BoardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("InvitedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("BoardMemberUId");

                    b.HasIndex("UserUId");

                    b.HasIndex("BoardUId", "UserUId")
                        .IsUnique();

                    b.ToTable("BoardMembers", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Card", b =>
                {
                    b.Property<string>("CardUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BackgroundUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("ListUId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("To Do");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardUId");

                    b.HasIndex("ListUId");

                    b.ToTable("Cards", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.CardDueDateReminderDelivery", b =>
                {
                    b.Property<string>("ReminderDeliveryId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CardUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("DueDateSnapshot")
                        .HasColumnType("datetime2");

                    b.Property<int>("Milestone")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ReminderDeliveryId");

                    b.HasIndex("CardUId", "Milestone")
                        .IsUnique();

                    b.ToTable("CardDueDateReminderDeliveries", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.CardLabel", b =>
                {
                    b.Property<string>("CardLabelUId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CardLabelUId");

                    b.HasIndex("CardUId");

                    b.ToTable("CardLabels");
                });

            modelBuilder.Entity("TodoAppAPI.Models.CardMember", b =>
                {
                    b.Property<string>("CardMemberUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CardUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Assignee");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("CardMemberUId");

                    b.HasIndex("UserUId");

                    b.HasIndex("CardUId", "UserUId")
                        .IsUnique();

                    b.ToTable("CardMembers", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Comment", b =>
                {
                    b.Property<string>("CommentUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("UserUId")
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("CommentUId");

                    b.HasIndex("CardUId");

                    b.HasIndex("UserUId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.FileUrl", b =>
                {
                    b.Property<string>("FileUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileUId");

                    b.HasIndex("CardUId");

                    b.ToTable("FileUrls", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.List", b =>
                {
                    b.Property<string>("ListUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BoardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("ListUId");

                    b.HasIndex("BoardUId");

                    b.ToTable("Lists", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Notification", b =>
                {
                    b.Property<string>("NotiId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorId")
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BoardId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CardId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Link")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ListId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Read")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("NotiId");

                    b.HasIndex("ActorId");

                    b.HasIndex("BoardId", "CreatedAt");

                    b.HasIndex("CardId", "CreatedAt");

                    b.HasIndex("RecipientId", "Read", "CreatedAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.PermissionAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionByUserUId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OldRole")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TargetUserUId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PermissionAudits", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "System Administrator",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Regular User",
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Guest User",
                            RoleName = "Guest"
                        });
                });

            modelBuilder.Entity("TodoAppAPI.Models.TodoItem", b =>
                {
                    b.Property<string>("TodoItemUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CardUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.HasKey("TodoItemUId");

                    b.HasIndex("CardUId");

                    b.ToTable("TodoItems", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.User", b =>
                {
                    b.Property<string>("UserUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsEmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsTwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Provider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("StatusAccount")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("VerificationTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationTokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("UserUId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.User2FABackupCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserUId");

                    b.ToTable("User2FABackupCodes", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserInboxCard", b =>
                {
                    b.Property<string>("UserUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CardUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("UserUId", "CardUId");

                    b.HasIndex("CardUId");

                    b.ToTable("UserInboxCards", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserOtp", b =>
                {
                    b.Property<string>("UserUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("UserUId");

                    b.ToTable("UserOtps", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserRecentBoard", b =>
                {
                    b.Property<string>("UserRecentBoardUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BoardUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("LastVisitedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("UserRecentBoardUId");

                    b.HasIndex("BoardUId");

                    b.HasIndex("LastVisitedAt");

                    b.HasIndex("UserUId");

                    b.ToTable("UserRecentBoard", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserSession", b =>
                {
                    b.Property<string>("UserUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("UserUId");

                    b.ToTable("UserSessions", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkflowDesign", b =>
                {
                    b.Property<string>("WorkflowDesignUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CreatedByUserUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("WorkspaceUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("WorkflowDesignUId");

                    b.HasIndex("CreatedByUserUId");

                    b.HasIndex("WorkspaceUId");

                    b.ToTable("WorkflowDesigns", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkflowEdge", b =>
                {
                    b.Property<string>("WorkflowEdgeUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EdgeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("dependency");

                    b.Property<bool>("IsReversed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceNodeUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TargetNodeUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkflowDesignUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("WorkflowEdgeUId");

                    b.HasIndex("TargetNodeUId");

                    b.HasIndex("WorkflowDesignUId");

                    b.HasIndex("SourceNodeUId", "TargetNodeUId")
                        .IsUnique();

                    b.ToTable("WorkflowEdges", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkflowNode", b =>
                {
                    b.Property<string>("WorkflowNodeUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Board");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionY")
                        .HasColumnType("float");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkflowDesignUId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("WorkflowNodeUId");

                    b.HasIndex("ReferenceId");

                    b.HasIndex("WorkflowDesignUId");

                    b.ToTable("WorkflowNodes", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Workspace", b =>
                {
                    b.Property<string>("WorkspaceUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Active");

                    b.HasKey("WorkspaceUId");

                    b.HasIndex("OwnerUId");

                    b.ToTable("Workspaces", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkspaceMembers", b =>
                {
                    b.Property<string>("WorkspaceMemberUId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Member");

                    b.Property<string>("UserUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkspaceUId")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("WorkspaceMemberUId");

                    b.HasIndex("UserUId");

                    b.HasIndex("WorkspaceUId", "UserUId")
                        .IsUnique();

                    b.ToTable("WorkspaceMembers", (string)null);
                });

            modelBuilder.Entity("TodoAppAPI.Models.Activity", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", null)
                        .WithMany("Activities")
                        .HasForeignKey("CardUId");

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("Activities")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.AnalysisReport", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "GeneratedBy")
                        .WithMany()
                        .HasForeignKey("GeneratedByUId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GeneratedBy");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Board", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("OwnedBoards")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.Workspace", "Workspace")
                        .WithMany("Boards")
                        .HasForeignKey("WorkspaceUId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TodoAppAPI.Models.BoardMember", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Board", "Board")
                        .WithMany("Members")
                        .HasForeignKey("BoardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("BoardMemberships")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Card", b =>
                {
                    b.HasOne("TodoAppAPI.Models.List", "List")
                        .WithMany("Cards")
                        .HasForeignKey("ListUId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("List");
                });

            modelBuilder.Entity("TodoAppAPI.Models.CardDueDateReminderDelivery", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany()
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TodoAppAPI.Models.CardLabel", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany("CardLabels")
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TodoAppAPI.Models.CardMember", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany("CardMembers")
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Comment", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany("Comments")
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.FileUrl", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany("FileUrls")
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TodoAppAPI.Models.List", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Board", "Board")
                        .WithMany("Lists")
                        .HasForeignKey("BoardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Notification", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "Actor")
                        .WithMany("SentNotifications")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("TodoAppAPI.Models.User", "Recipient")
                        .WithMany("ReceivedNotifications")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("TodoAppAPI.Models.TodoItem", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany("TodoItems")
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("TodoAppAPI.Models.User", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TodoAppAPI.Models.User2FABackupCode", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("BackupCodes")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserInboxCard", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Card", "Card")
                        .WithMany("UserInboxCards")
                        .HasForeignKey("CardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("InboxCards")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserOtp", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithOne("UserOtp")
                        .HasForeignKey("TodoAppAPI.Models.UserOtp", "UserUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserRecentBoard", b =>
                {
                    b.HasOne("TodoAppAPI.Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.UserSession", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithOne("Session")
                        .HasForeignKey("TodoAppAPI.Models.UserSession", "UserUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkflowDesign", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserUId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TodoAppAPI.Models.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkflowEdge", b =>
                {
                    b.HasOne("TodoAppAPI.Models.WorkflowNode", "SourceNode")
                        .WithMany("SourceEdges")
                        .HasForeignKey("SourceNodeUId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.WorkflowNode", "TargetNode")
                        .WithMany("TargetEdges")
                        .HasForeignKey("TargetNodeUId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.WorkflowDesign", "WorkflowDesign")
                        .WithMany("Edges")
                        .HasForeignKey("WorkflowDesignUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");

                    b.Navigation("WorkflowDesign");
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkflowNode", b =>
                {
                    b.HasOne("TodoAppAPI.Models.WorkflowDesign", "WorkflowDesign")
                        .WithMany("Nodes")
                        .HasForeignKey("WorkflowDesignUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDesign");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Workspace", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "Owner")
                        .WithMany("OwnedWorkspaces")
                        .HasForeignKey("OwnerUId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkspaceMembers", b =>
                {
                    b.HasOne("TodoAppAPI.Models.User", "User")
                        .WithMany("WorkspaceMemberships")
                        .HasForeignKey("UserUId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TodoAppAPI.Models.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceUId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Board", b =>
                {
                    b.Navigation("Lists");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Card", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CardLabels");

                    b.Navigation("CardMembers");

                    b.Navigation("Comments");

                    b.Navigation("FileUrls");

                    b.Navigation("TodoItems");

                    b.Navigation("UserInboxCards");
                });

            modelBuilder.Entity("TodoAppAPI.Models.List", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TodoAppAPI.Models.User", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("BackupCodes");

                    b.Navigation("BoardMemberships");

                    b.Navigation("Comments");

                    b.Navigation("InboxCards");

                    b.Navigation("OwnedBoards");

                    b.Navigation("OwnedWorkspaces");

                    b.Navigation("ReceivedNotifications");

                    b.Navigation("SentNotifications");

                    b.Navigation("Session");

                    b.Navigation("UserOtp");

                    b.Navigation("WorkspaceMemberships");
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkflowDesign", b =>
                {
                    b.Navigation("Edges");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("TodoAppAPI.Models.WorkflowNode", b =>
                {
                    b.Navigation("SourceEdges");

                    b.Navigation("TargetEdges");
                });

            modelBuilder.Entity("TodoAppAPI.Models.Workspace", b =>
                {
                    b.Navigation("Boards");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
