// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo1hUSZkzQikrjFt7MfdU_sKpqYWm7CAA',
    appId: '1:371567831919:web:ab7c590edda9a2876a569a',
    messagingSenderId: '371567831919',
    projectId: 'kabo-project',
    authDomain: 'kabo-project.firebaseapp.com',
    storageBucket: 'kabo-project.firebasestorage.app',
    measurementId: 'G-KPBR6DTSK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDJ0Fui5maydLIItgA36MtNIVX1K-o754',
    appId: '1:371567831919:android:a1dcab9945bc9fdd6a569a',
    messagingSenderId: '371567831919',
    projectId: 'kabo-project',
    storageBucket: 'kabo-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP1Sj13czXTa8ZSI2FElblZ0ORXPRsg-I',
    appId: '1:371567831919:ios:e95843f2d5b10f3f6a569a',
    messagingSenderId: '371567831919',
    projectId: 'kabo-project',
    storageBucket: 'kabo-project.firebasestorage.app',
    iosBundleId: 'com.example.apptreolon',
  );
}
